### ISSUE TITLE
Commons CLI Download mirror is no longer reachable

### ISSUE THREAD

**Issue by LehrChristoph** [t-crest/poseidon#4]
Hi,

I tried building poseidon and I saw that the download mirror is no long available.
There is a new version of the commons CLI : 1.5.0 http://mirrors.dotsrc.org/apache/commons/cli/source/commons-cli-1.5.0-src.tar.gz
Version 1.4 is still available via apache under https://archive.apache.org/dist/commons/cli/source/commons-cli-1.4-src.tar.gz

**Comment by schoeberl** [comment]
Yes, this is a known issue. Could you fix it with a PR?

**Comment by LehrChristoph** [comment]
I created this PR with the updated download link https://github.com/t-crest/poseidon/pull/5

**Comment by schoeberl** [comment]
I guess we can then close this.
